on:
  push:
    branches:
      - tests
      
defaults:
  run:
    working-directory: ./src/tests/googletest

name: GoogleTest

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        cd /home/runner/work/FIMS-software
        cmake -S . -B build 
        
    - name: Build
      run: |
        cd build 
        cmake --build .
        
    - name: Test
      run: |
        ctest 